on:
  push:
    branches:
    - main
  pull_request:

jobs:
  install_fdb:
    name: Install FDB ${{ matrix.fdb_version }} on ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # macOS test variations
          - os: macos-13
            fdb_version: '7.3.66'
          - os: macos-14
            fdb_version: '7.3.66'

          # Linux test variations
          - os: ubuntu-latest
            fdb_version: '6.3.25'
          - os: ubuntu-latest
            fdb_version: '7.1.59'
          - os: ubuntu-latest
            fdb_version: '7.3.66'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install FoundationDB
        uses: ./

      - name: foundationdb status
        run: fdbcli --exec status
